// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserReplayTextSnapshotFormat } from "./BrowserReplayTextSnapshotFormat";
import type { BrowserSessionState } from "./BrowserSessionState";
import type { DynamicToolCallStatus } from "./DynamicToolCallStatus";

export type BrowserReplayFrame = { sequenceNumber: number, sourceItemId: string, tool: string, status: DynamicToolCallStatus, imageUrl?: string | null, textSnapshot?: string | null, textSnapshotFormat?: BrowserReplayTextSnapshotFormat | null, browserState?: BrowserSessionState | null, };
