// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserSessionState } from "./BrowserSessionState";

export type BrowserSessionUpdatedNotification = { browserSessionId: string, browserState: BrowserSessionState, };
