// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { DynamicToolCallOutputContentItem } from "./DynamicToolCallOutputContentItem";

export type DynamicToolCallResponse = { contentItems: Array<DynamicToolCallOutputContentItem>, success: boolean, 
/**
 * Optional client-approved replacement arguments. When present, this must
 * fully match the existing registered schema for the same dynamic tool.
 */
approvedArguments: JsonValue | null, };
