// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAgentConfigMigrationItemType } from "./ExternalAgentConfigMigrationItemType";

export type ExternalAgentConfigMigrationItem = { itemType: ExternalAgentConfigMigrationItemType, description: string, 
/**
 * Null or empty means home-scoped migration; non-empty means repo-scoped migration.
 */
cwd: string | null, /**
 * Optional link target for "from" (file or directory path).
 */
sourcePath: string | null, /**
 * Optional link target for "to" (file or directory path).
 */
targetPath: string | null, /**
 * Optional copyable count (e.g., number of skills folders).
 */
copyCount: number | null, };
