// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { FileSystemSandboxPolicy } from "../FileSystemSandboxPolicy";

/**
 * Create a directory on the host filesystem.
 */
export type FsCreateDirectoryParams = { 
/**
 * Absolute directory path to create.
 */
path: AbsolutePathBuf, 
/**
 * Whether parent directories should also be created. Defaults to `true`.
 */
recursive?: boolean | null, 
/**
 * Optional sandbox policy for re-invoking this filesystem operation under a sandbox.
 */
sandboxPolicy?: FileSystemSandboxPolicy | null, };
