// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { FileSystemSandboxPolicy } from "../FileSystemSandboxPolicy";

/**
 * Request metadata for an absolute path.
 */
export type FsGetMetadataParams = { 
/**
 * Absolute path to inspect.
 */
path: AbsolutePathBuf, 
/**
 * Optional sandbox policy for re-invoking this filesystem operation under a sandbox.
 */
sandboxPolicy?: FileSystemSandboxPolicy | null, };
