// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { SandboxPolicy } from "./SandboxPolicy";

/**
 * Request metadata for an absolute path.
 */
export type FsGetMetadataParams = {
/**
 * Absolute path to inspect.
 */
path: AbsolutePathBuf,
/**
 * Optional sandbox policy for this filesystem metadata lookup.
 */
sandboxPolicy?: SandboxPolicy | null,
/**
 * Optional cwd to resolve legacy sandbox workspace roots against.
 */
cwd?: AbsolutePathBuf | null, };
