// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { FileSystemSandboxPolicy } from "../FileSystemSandboxPolicy";

/**
 * List direct child names for a directory.
 */
export type FsReadDirectoryParams = { 
/**
 * Absolute directory path to read.
 */
path: AbsolutePathBuf, 
/**
 * Optional sandbox policy for re-invoking this filesystem operation under a sandbox.
 */
sandboxPolicy?: FileSystemSandboxPolicy | null, };
