// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { SandboxPolicy } from "./SandboxPolicy";

/**
 * Read a file from the host filesystem.
 */
export type FsReadFileParams = { 
/**
 * Absolute path to read.
 */
path: AbsolutePathBuf, 
/**
 * Optional sandbox policy for this filesystem read.
 */
sandboxPolicy?: SandboxPolicy | null, 
/**
 * Optional cwd to resolve legacy sandbox workspace roots against.
 */
cwd?: AbsolutePathBuf | null, };
