// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { SandboxPolicy } from "./SandboxPolicy";

/**
 * Write a file on the host filesystem.
 */
export type FsWriteFileParams = {
/**
 * Absolute path to write.
 */
path: AbsolutePathBuf,
/**
 * File contents encoded as base64.
 */
dataBase64: string,
/**
 * Optional sandbox policy for this filesystem write.
 */
sandboxPolicy?: SandboxPolicy | null,
/**
 * Optional cwd to resolve legacy sandbox workspace roots against.
 */
cwd?: AbsolutePathBuf | null, };
