// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update user-owned inbox tracking state for one record.
 */
export type InboxUpdateParams = { 
/**
 * Exact inbox filename under `$CODEX_HOME/inbox`, for example
 * `thread__20260319T170500Z__slack__C01234567__1712345678.000000.json`.
 */
threadId: string, 
/**
 * RFC 3339 timestamp to store in `tracking.last_read_at`.
 */
lastReadAt: string, };
