// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Tracked inbox records are returned as the on-disk JSON shape defined by the
 * sort-inbox skill's thread record format.
 */
export type InboxListResponse = { data: Array<JsonValue>, };
