// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { GuardianApprovalReview } from "./GuardianApprovalReview";

/**
 * [UNSTABLE] Temporary notification payload for guardian automatic approval
 * review.
 *
 * TODO(ccunningham): Attach guardian review state to the reviewed tool item's
 * lifecycle instead of sending separate standalone review notifications so the
 * app-server API can persist and replay review state via `thread/read`.
 */
export type ItemGuardianApprovalReviewStartedNotification = { threadId: string, turnId: string, 
/**
 * Deprecated alias for `review_id`, retained for backwards compatibility.
 */
targetItemId: string, 
/**
 * Stable guardian review identifier for matching started/completed events.
 */
reviewId: string | null, parentToolItemId: string | null, review: GuardianApprovalReview, action: JsonValue | null, };
