// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { LogEntryLevel } from "./LogEntryLevel";
import type { LogSpanContext } from "./LogSpanContext";

export type LogEntryNotification = { timestamp: bigint, level: LogEntryLevel, target: string, message: string, fields: { [key in string]?: JsonValue }, span: LogSpanContext | null, };
