// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { McpElicitationObjectType } from "./McpElicitationObjectType";
import type { McpElicitationPrimitiveSchema } from "./McpElicitationPrimitiveSchema";

/**
 * Typed form schema for MCP `elicitation/create` requests.
 *
 * This mirrors the `requestedSchema` shape from the MCP `ElicitRequestFormParams` schema while
 * preserving extension keywords such as Codex-specific `x-codex-*` metadata.
 */
export type McpElicitationSchema = { $schema?: string, type: McpElicitationObjectType, title?: string, properties: { [key in string]?: McpElicitationPrimitiveSchema }, required?: Array<string>, description?: string, } & ({ [key in string]?: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null });
