// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { McpElicitationIntegerType } from "./McpElicitationIntegerType";

export type McpElicitationIntegerSchema = { type: McpElicitationIntegerType, title?: string, description?: string, minimum?: bigint, maximum?: bigint, } & ({ [key in string]?: number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null });
