// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResponseItem } from "../ResponseItem";
import type { JsonValue } from "../serde_json/JsonValue";

export type ModelRequestEnvelope = { model: string, instructions: string, input: Array<ResponseItem>, tools: Array<JsonValue>, toolChoice: string, parallelToolCalls: boolean, reasoning: JsonValue | null, store: boolean, stream: boolean, include: Array<string>, serviceTier: string | null, promptCacheKey: string | null, text: JsonValue | null, requestHeaders: { [key in string]?: string } | null, };
