// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRequestError } from "./ModelRequestError";

export type ModelRequestFailedNotification = { threadId: string, turnId: string, requestId: string, error: ModelRequestError, };
