// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionProfileAmendment } from "./PermissionProfileAmendment";

export type PermissionGrantScope = { "type": "turn" } | { "type": "session" } | { "type": "persist", permissionProfileAmendment: PermissionProfileAmendment, };
