// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomPrompt } from "../CustomPrompt";

export type PromptListResponse = { environmentId: string, prompts: Array<CustomPrompt>, };
