// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SdkDelegationConfig = { 
/**
 * Base URL for the host-managed Responses bridge reachable by the Codex runtime.
 */
bridgeUrl: string, 
/**
 * Optional model-provider id to register for this thread.
 * Defaults to `codex-sdk-v2`.
 */
modelProviderId: string | null, 
/**
 * Optional stream idle timeout override for the delegated provider.
 */
streamIdleTimeoutMs: bigint | null, };
