// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadMetadataGitInfoUpdateParams } from "./ThreadMetadataGitInfoUpdateParams";

export type ThreadMetadataUpdateParams = { threadId: string, 
/**
 * Replace the stored client-defined metadata for this thread.
 */
metadata?: { [key in string]?: string } | null,
/**
 * Patch the stored Git metadata for this thread.
 * Omit a field to leave it unchanged, set it to `null` to clear it, or
 * provide a string to replace the stored value.
 */
gitInfo?: ThreadMetadataGitInfoUpdateParams | null, };
