// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadJob } from "./ThreadJob";

export type ThreadJobUpdatedNotification = { threadId: string, jobs: Array<ThreadJob>, };
