// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadFrameworkEventType } from "./ThreadFrameworkEventType";

export type ThreadFrameworkEventNotification = { threadId: string, eventType: ThreadFrameworkEventType, message: string, };
