// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadContextReadParams = { threadId: string, 
/**
 * When true, include every contributing row instead of merging repeated labels.
 */
verbose?: boolean, };
