// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadContextWindowSection } from "./ThreadContextWindowSection";

export type ThreadContextWindowBreakdown = { modelContextWindow: bigint | null, totalTokens: bigint, sections: Array<ThreadContextWindowSection>, };
