// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadContextWindowDetail } from "./ThreadContextWindowDetail";

export type ThreadContextWindowSection = { label: string, tokens: bigint, details: Array<ThreadContextWindowDetail>, };
