// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebSearchToolConfig } from "../WebSearchToolConfig";
import type { ToolExecutionMode } from "./ToolExecutionMode";

export type ToolsV2 = { web_search: WebSearchToolConfig | null, view_image: boolean | null, execution_mode: ToolExecutionMode | null, };
