// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolFeatureConfigV2 } from "./ToolFeatureConfigV2";
import type { WebSearchFeatureConfigV2 } from "./WebSearchFeatureConfigV2";

export type ToolsV2 = { disable_defaults: boolean | null, shell: ToolFeatureConfigV2 | null, filesystem: ToolFeatureConfigV2 | null, javascript: ToolFeatureConfigV2 | null, agents: ToolFeatureConfigV2 | null, agent_jobs: ToolFeatureConfigV2 | null, planning: ToolFeatureConfigV2 | null, user_input: ToolFeatureConfigV2 | null, web_search: WebSearchFeatureConfigV2 | null, image_generation: ToolFeatureConfigV2 | null, document_generation: ToolFeatureConfigV2 | null, 
/**
 * Legacy enablement for the `view_image` capability.
 */
view_image: boolean | null, };
