// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebSearchToolConfigValue } from "../WebSearchToolConfigValue";

export type ToolsV2 = { web_search: WebSearchToolConfigValue | null, view_image: boolean | null, };
