[mypy]
python_version = 3.10
mypy_path = sdk/python/src
check_untyped_defs = True
warn_unused_ignores = True
no_implicit_optional = True
exclude = ^sdk/python/src/codex_app_server/generated/

[mypy-codex_app_server.api]
ignore_errors = True

[mypy-codex_app_server.async_client]
ignore_errors = True

[mypy-codex_app_server.client]
ignore_errors = True

[mypy-codex_app_server.generated.*]
ignore_errors = True
