pub mod auth;
pub mod token_data;

mod device_code_auth;
mod dotenv_api_key;
mod onboard_oauth_helper;
mod pkce;
mod server;

pub use codex_client::BuildCustomCaTransportError as BuildLoginHttpClientError;
pub use device_code_auth::DeviceCode;
pub use device_code_auth::complete_device_code_login;
pub use device_code_auth::request_device_code;
pub use device_code_auth::run_device_code_login;
pub use server::LoginServer;
pub use server::ServerOptions;
pub use server::ShutdownHandle;
pub use server::run_login_server;

pub use auth::AuthConfig;
pub use auth::AuthCredentialsStoreMode;
pub use auth::AuthDotJson;
pub use auth::AuthManager;
pub use auth::CLIENT_ID;
pub use auth::CODEX_API_KEY_ENV_VAR;
pub use auth::CodexAuth;
pub use auth::OPENAI_API_KEY_ENV_VAR;
pub use auth::REFRESH_TOKEN_URL_OVERRIDE_ENV_VAR;
pub use auth::RefreshTokenError;
pub use auth::UnauthorizedRecovery;
pub use auth::default_client;
pub use auth::enforce_login_restrictions;
pub use auth::load_auth_dot_json;
pub use auth::login_with_api_key;
pub use auth::logout;
pub use auth::read_openai_api_key_from_env;
pub use auth::save_auth;
pub use codex_app_server_protocol::AuthMode;
pub use dotenv_api_key::upsert_dotenv_api_key;
pub use dotenv_api_key::validate_dotenv_target;
pub use onboard_oauth_helper::ApiProvisionOptions;
pub use onboard_oauth_helper::HelperError as OnboardOauthHelperError;
pub use onboard_oauth_helper::PendingApiProvisioning;
pub use onboard_oauth_helper::ProvisionedApiKey;
pub use onboard_oauth_helper::run_from_env as run_onboard_oauth_helper_from_env;
pub use onboard_oauth_helper::start_api_provisioning;
pub use token_data::TokenData;
