// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApprovalSummary = { request_count: number, approved_count: number, approved_with_amendment_count: number, approved_for_session_count: number, approved_with_network_policy_allow_count: number, denied_with_network_policy_deny_count: number, denied_count: number, abort_count: number, };
