// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRequestFailedNotification } from "./v2/ModelRequestFailedNotification";
import type { ModelStreamEventNotification } from "./v2/ModelStreamEventNotification";
import type { ModelStreamMetadataNotification } from "./v2/ModelStreamMetadataNotification";

export type ClientNotification = { "method": "initialized" } | { "method": "model/streamMetadata", "params": ModelStreamMetadataNotification } | { "method": "model/streamEvent", "params": ModelStreamEventNotification } | { "method": "model/requestFailed", "params": ModelRequestFailedNotification };
