// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Access mode for a filesystem entry.
 *
 * When two equally specific entries target the same path, we compare these by
 * conflict precedence rather than by capability breadth: `none` beats
 * `write`, and `write` beats `read`.
 */
export type FileSystemAccessMode = "read" | "write" | "none";
