// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetworkPermissions = { enabled: boolean | null, allowed_domains: Array<string> | null, allow_local_binding: boolean | null, };
