// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnItemMetadata } from "./TurnItemMetadata";

export type ReasoningItem = { id: string, summary_text: Array<string>, raw_content: Array<string>, metadata?: TurnItemMetadata, };
