// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewDecisionMetadata } from "./ReviewDecisionMetadata";
import type { UserMessageType } from "./UserMessageType";

export type ResponseItemMetadata = { user_message_type?: UserMessageType, is_tool_call_escalated?: boolean, review_decision?: ReviewDecisionMetadata, };
