// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserMessageType } from "./UserMessageType";

export type ResponseItemMetadata = { user_message_type?: UserMessageType, 
/**
 * Client-visible UUID generated by Codex for this item.
 */
uuid?: string, };
