// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserMessageType } from "./UserMessageType";

export type ResponseItemMessageMetadata = { user_message_type?: UserMessageType, 
/**
 * Client-visible metadata ID generated by Codex for this item.
 */
metadata_id: string, };
