// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewDecisionMetadata = "approved" | "denied" | "abort" | "approved_for_session" | "approved_with_amendment" | "approved_with_network_policy_allow" | "denied_with_network_policy_deny";
