// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionSourceMetadata = "cli" | "vscode" | "exec" | "mcp" | "subagent_review" | "subagent_compact" | "subagent_memory_consolidation" | "subagent_thread_spawn" | "subagent_other" | "unknown";
