// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionSourceMetadata = "user" | "agent_guardian" | "agent_review" | "agent_spawned" | "agent_compaction" | "agent_memory" | "agent_other" | "unknown";
