// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EscalationStatus } from "./EscalationStatus";
import type { UserMessagePersonality } from "./UserMessagePersonality";
import type { UserMessageSandboxPolicy } from "./UserMessageSandboxPolicy";
import type { UserMessageType } from "./UserMessageType";

export type UserMessageMetadata = { is_plan_mode?: boolean, is_tool_call_escalated?: boolean, escalation_status?: EscalationStatus, sandbox_policy?: UserMessageSandboxPolicy, user_message_type?: UserMessageType, personality?: UserMessagePersonality, };
