mod discoverable;
mod injection;
mod manager;
mod render;
#[cfg(test)]
pub(crate) mod test_support;

pub use codex_capabilities::plugins::MarketplaceError;
pub use codex_capabilities::plugins::MarketplacePluginAuthPolicy;
pub use codex_capabilities::plugins::MarketplacePluginInstallPolicy;
pub use codex_capabilities::plugins::MarketplacePluginPolicy;
pub use codex_capabilities::plugins::MarketplacePluginSource;
pub use codex_capabilities::plugins::PluginId;
pub use codex_capabilities::plugins::PluginManifestInterface;
pub(crate) use codex_capabilities::plugins::PluginManifestPaths;
pub use codex_capabilities::plugins::RemotePluginFetchError;
pub use codex_capabilities::plugins::collect_plugin_enabled_candidates;
pub(crate) use codex_capabilities::plugins::curated_plugins_repo_path;
pub use codex_capabilities::plugins::fetch_remote_featured_plugin_ids;
pub(crate) use codex_capabilities::plugins::load_plugin_manifest;
pub(crate) use codex_capabilities::plugins::read_curated_plugins_sha;
pub(crate) use codex_capabilities::plugins::sync_openai_plugins_repo;
pub(crate) use discoverable::list_tool_suggest_discoverable_plugins;
pub(crate) use injection::build_plugin_injections;
pub use manager::AppConnectorId;
pub use manager::ConfiguredMarketplace;
pub use manager::ConfiguredMarketplacePlugin;
pub use manager::LoadedPlugin;
pub use manager::OPENAI_CURATED_MARKETPLACE_NAME;
pub use manager::PluginCapabilitySummary;
pub use manager::PluginDetail;
pub use manager::PluginInstallError;
pub use manager::PluginInstallOutcome;
pub use manager::PluginInstallRequest;
pub use manager::PluginLoadOutcome;
pub use manager::PluginReadOutcome;
pub use manager::PluginReadRequest;
pub use manager::PluginRemoteSyncError;
pub use manager::PluginTelemetryMetadata;
pub use manager::PluginUninstallError;
pub use manager::PluginsManager;
pub use manager::RemotePluginSyncResult;
pub use manager::installed_plugin_telemetry_metadata;
pub use manager::load_plugin_apps;
pub use manager::load_plugin_mcp_servers;
pub(crate) use manager::plugin_namespace_for_skill_path;
pub use manager::plugin_telemetry_metadata_from_root;
pub(crate) use render::render_explicit_plugin_instructions;
pub(crate) use render::render_plugins_section;
