use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use codex_protocol::models::ShellCommandToolCallParams;
use codex_protocol::models::function_call_output_content_items_to_text;
use codex_protocol::protocol::AskForApproval;
use codex_protocol::protocol::EventMsg;
use codex_protocol::protocol::ExecCommandStatus;
use codex_protocol::protocol::ReviewDecision;
use pretty_assertions::assert_eq;

use crate::codex::make_session_and_context;
use crate::codex::make_session_and_context_with_rx;
use crate::exec_env::create_env;
use crate::is_safe_command::is_known_safe_command;
use crate::powershell::try_find_powershell_executable_blocking;
use crate::powershell::try_find_pwsh_executable_blocking;
use crate::sandboxing::SandboxPermissions;
use crate::shell::Shell;
use crate::shell::ShellType;
use crate::shell_snapshot::ShellSnapshot;
use crate::state::ActiveTurn;
use crate::tools::context::ToolInvocation;
use crate::tools::context::ToolPayload;
use crate::tools::handlers::ShellCommandHandler;
use crate::tools::handlers::ShellHandler;
use crate::tools::registry::ToolHandler;
use crate::turn_diff_tracker::TurnDiffTracker;
use tokio::sync::watch;
use tokio::time::timeout;

/// The logic for is_known_safe_command() has heuristics for known shells,
/// so we must ensure the commands generated by [ShellCommandHandler] can be
/// recognized as safe if the `command` is safe.
#[test]
fn commands_generated_by_shell_command_handler_can_be_matched_by_is_known_safe_command() {
    let bash_shell = Shell {
        shell_type: ShellType::Bash,
        shell_path: PathBuf::from("/bin/bash"),
        shell_snapshot: crate::shell::empty_shell_snapshot_receiver(),
    };
    assert_safe(&bash_shell, "ls -la");

    let zsh_shell = Shell {
        shell_type: ShellType::Zsh,
        shell_path: PathBuf::from("/bin/zsh"),
        shell_snapshot: crate::shell::empty_shell_snapshot_receiver(),
    };
    assert_safe(&zsh_shell, "ls -la");

    if let Some(path) = try_find_powershell_executable_blocking() {
        let powershell = Shell {
            shell_type: ShellType::PowerShell,
            shell_path: path.to_path_buf(),
            shell_snapshot: crate::shell::empty_shell_snapshot_receiver(),
        };
        assert_safe(&powershell, "ls -Name");
    }

    if let Some(path) = try_find_pwsh_executable_blocking() {
        let pwsh = Shell {
            shell_type: ShellType::PowerShell,
            shell_path: path.to_path_buf(),
            shell_snapshot: crate::shell::empty_shell_snapshot_receiver(),
        };
        assert_safe(&pwsh, "ls -Name");
    }
}

fn assert_safe(shell: &Shell, command: &str) {
    assert!(is_known_safe_command(
        &shell.derive_exec_args(command, /* use_login_shell */ true)
    ));
    assert!(is_known_safe_command(
        &shell.derive_exec_args(command, /* use_login_shell */ false)
    ));
}

fn tool_output_text(output: &crate::tools::context::FunctionToolOutput) -> String {
    function_call_output_content_items_to_text(&output.body).expect("tool output text")
}

#[tokio::test]
async fn shell_command_handler_to_exec_params_uses_session_shell_and_turn_context() {
    let (session, turn_context) = make_session_and_context().await;

    let command = "echo hello".to_string();
    let workdir = Some("subdir".to_string());
    let login = None;
    let timeout_ms = Some(1234);
    let sandbox_permissions = SandboxPermissions::RequireEscalated;
    let justification = Some("because tests".to_string());

    let expected_command = session.user_shell().derive_exec_args(&command, true);
    let expected_cwd = turn_context.resolve_path(workdir.clone());
    let expected_env = create_env(
        &turn_context.shell_environment_policy,
        Some(session.conversation_id),
    );

    let params = ShellCommandToolCallParams {
        command,
        workdir,
        login,
        timeout_ms,
        sandbox_permissions: Some(sandbox_permissions),
        additional_permissions: None,
        prefix_rule: None,
        justification: justification.clone(),
    };

    let exec_params = ShellCommandHandler::to_exec_params(
        &params,
        &session,
        &turn_context,
        session.conversation_id,
        true,
    )
    .expect("login shells should be allowed");

    // ExecParams cannot derive Eq due to the CancellationToken field, so we manually compare the fields.
    assert_eq!(exec_params.command, expected_command);
    assert_eq!(exec_params.cwd, expected_cwd);
    assert_eq!(exec_params.env, expected_env);
    assert_eq!(exec_params.network, turn_context.network);
    assert_eq!(exec_params.expiration.timeout_ms(), timeout_ms);
    assert_eq!(exec_params.sandbox_permissions, sandbox_permissions);
    assert_eq!(exec_params.justification, justification);
    assert_eq!(exec_params.arg0, None);
}

#[test]
fn shell_command_handler_respects_explicit_login_flag() {
    let (_tx, shell_snapshot) = watch::channel(Some(Arc::new(ShellSnapshot {
        path: PathBuf::from("/tmp/snapshot.sh"),
        cwd: PathBuf::from("/tmp"),
    })));
    let shell = Shell {
        shell_type: ShellType::Bash,
        shell_path: PathBuf::from("/bin/bash"),
        shell_snapshot,
    };

    let login_command = ShellCommandHandler::base_command(&shell, "echo login shell", true);
    assert_eq!(
        login_command,
        shell.derive_exec_args("echo login shell", true)
    );

    let non_login_command =
        ShellCommandHandler::base_command(&shell, "echo non login shell", false);
    assert_eq!(
        non_login_command,
        shell.derive_exec_args("echo non login shell", false)
    );
}

#[tokio::test]
async fn shell_command_handler_defaults_to_non_login_when_disallowed() {
    let (session, turn_context) = make_session_and_context().await;
    let params = ShellCommandToolCallParams {
        command: "echo hello".to_string(),
        workdir: None,
        login: None,
        timeout_ms: None,
        sandbox_permissions: None,
        additional_permissions: None,
        prefix_rule: None,
        justification: None,
    };

    let exec_params = ShellCommandHandler::to_exec_params(
        &params,
        &session,
        &turn_context,
        session.conversation_id,
        false,
    )
    .expect("non-login shells should still be allowed");

    assert_eq!(
        exec_params.command,
        session.user_shell().derive_exec_args("echo hello", false)
    );
}

#[test]
fn shell_command_handler_rejects_login_when_disallowed() {
    let err = ShellCommandHandler::resolve_use_login_shell(Some(true), false)
        .expect_err("explicit login should be rejected");

    assert!(
        err.to_string()
            .contains("login shell is disabled by config"),
        "unexpected error: {err}"
    );
}

#[tokio::test]
async fn shell_handler_retry_emits_single_begin_before_approval_request() {
    let (session, mut turn_context, rx) = make_session_and_context_with_rx().await;
    *session.active_turn.lock().await = Some(ActiveTurn::default());
    Arc::get_mut(&mut turn_context)
        .expect("single turn context ref")
        .approval_policy
        .set(AskForApproval::OnFailure)
        .expect("test setup should allow updating approval policy");

    let temp_dir = tempfile::tempdir_in(
        turn_context
            .cwd
            .parent()
            .expect("workspace cwd should have a parent"),
    )
    .expect("create temp dir outside workspace");
    let file_path = temp_dir.path().join("outside-sandbox.txt");
    let expected_stdout = "hello from outside sandbox\n".to_string();
    std::fs::write(&file_path, expected_stdout.as_bytes()).expect("write readable file");

    let command = if cfg!(windows) {
        vec![
            "cmd.exe".to_string(),
            "/C".to_string(),
            format!("type \"{}\"", file_path.display()),
        ]
    } else {
        vec!["/bin/cat".to_string(), file_path.display().to_string()]
    };

    let tracker = Arc::new(tokio::sync::Mutex::new(TurnDiffTracker::new()));
    let call_id = "call-1".to_string();
    let handler = ShellHandler;
    let handle: tokio::task::JoinHandle<
        Result<crate::tools::context::FunctionToolOutput, crate::function_tool::FunctionCallError>,
    > = tokio::spawn({
        let session = Arc::clone(&session);
        let turn_context = Arc::clone(&turn_context);
        let tracker = Arc::clone(&tracker);
        let command = command.clone();
        let call_id = call_id.clone();
        async move {
            handler
                .handle(ToolInvocation {
                    session,
                    turn: turn_context.clone(),
                    tracker,
                    call_id: call_id.clone(),
                    tool_name: "shell".to_string(),
                    tool_namespace: None,
                    payload: ToolPayload::Function {
                        arguments: serde_json::json!({
                            "command": command,
                            "workdir": Some(turn_context.cwd.to_string_lossy().to_string()),
                            "timeout_ms": 1_000u64,
                            "sandbox_permissions": SandboxPermissions::UseDefault,
                        })
                        .to_string(),
                    },
                })
                .await
        }
    });

    let mut begin_count = 0usize;
    let mut begin_idx = None;
    let mut event_idx = 0usize;
    let approval_idx = loop {
        let event = timeout(Duration::from_secs(5), rx.recv())
            .await
            .expect("timed out waiting for approval flow event")
            .expect("approval flow event missing");
        match event.msg {
            EventMsg::ExecCommandBegin(begin) if begin.call_id == call_id => {
                begin_count += 1;
                if begin_idx.is_none() {
                    begin_idx = Some(event_idx);
                }
            }
            EventMsg::ExecApprovalRequest(request) if request.call_id == call_id => {
                break event_idx;
            }
            _ => {}
        }
        event_idx += 1;
    };

    assert_eq!(begin_count, 1);
    assert_eq!(begin_idx, Some(0));
    assert!(
        approval_idx > begin_idx.expect("begin event should exist"),
        "approval request should follow the begin event"
    );

    session
        .notify_approval(&call_id, ReviewDecision::Approved)
        .await;

    let end_event = loop {
        let event = timeout(Duration::from_secs(5), rx.recv())
            .await
            .expect("timed out waiting for exec end event")
            .expect("exec end event missing");
        match event.msg {
            EventMsg::ExecCommandBegin(begin) if begin.call_id == call_id => {
                begin_count += 1;
            }
            EventMsg::ExecCommandEnd(end) if end.call_id == call_id => {
                break end;
            }
            _ => {}
        }
    };

    let _response = timeout(Duration::from_secs(5), handle)
        .await
        .expect("timed out waiting for shell handler")
        .expect("shell handler join error")
        .expect("shell handler should succeed");

    assert_eq!(begin_count, 1);
    assert_eq!(end_event.status, ExecCommandStatus::Completed);
    assert_eq!(end_event.command, command);
    assert_eq!(end_event.stdout, expected_stdout);
    assert_eq!(end_event.exit_code, 0);
}

#[tokio::test]
async fn shell_handler_retry_override_keeps_single_begin_and_reports_override() {
    let (session, mut turn_context, rx) = make_session_and_context_with_rx().await;
    *session.active_turn.lock().await = Some(ActiveTurn::default());
    Arc::get_mut(&mut turn_context)
        .expect("single turn context ref")
        .approval_policy
        .set(AskForApproval::OnFailure)
        .expect("test setup should allow updating approval policy");

    let temp_dir = tempfile::tempdir_in(
        turn_context
            .cwd
            .parent()
            .expect("workspace cwd should have a parent"),
    )
    .expect("create temp dir outside workspace");
    let file_path = temp_dir.path().join("outside-sandbox.txt");
    std::fs::write(&file_path, b"should not run\n").expect("write readable file");

    let requested_command = if cfg!(windows) {
        vec![
            "cmd.exe".to_string(),
            "/C".to_string(),
            format!("type \"{}\"", file_path.display()),
        ]
    } else {
        vec!["/bin/cat".to_string(), file_path.display().to_string()]
    };
    let override_command = if cfg!(windows) {
        vec![
            "cmd.exe".to_string(),
            "/C".to_string(),
            "echo override-after-retry".to_string(),
        ]
    } else {
        vec!["/bin/echo".to_string(), "override-after-retry".to_string()]
    };
    let tracker = Arc::new(tokio::sync::Mutex::new(TurnDiffTracker::new()));
    let call_id = "call-retry-override".to_string();
    let handler = ShellHandler;
    let handle: tokio::task::JoinHandle<
        Result<crate::tools::context::FunctionToolOutput, crate::function_tool::FunctionCallError>,
    > = tokio::spawn({
        let session = Arc::clone(&session);
        let turn_context = Arc::clone(&turn_context);
        let tracker = Arc::clone(&tracker);
        let requested_command = requested_command.clone();
        let call_id = call_id.clone();
        async move {
            handler
                .handle(ToolInvocation {
                    session,
                    turn: turn_context.clone(),
                    tracker,
                    call_id: call_id.clone(),
                    tool_name: "shell".to_string(),
                    tool_namespace: None,
                    payload: ToolPayload::Function {
                        arguments: serde_json::json!({
                            "command": requested_command,
                            "workdir": Some(turn_context.cwd.to_string_lossy().to_string()),
                            "timeout_ms": 1_000u64,
                            "sandbox_permissions": SandboxPermissions::UseDefault,
                        })
                        .to_string(),
                    },
                })
                .await
        }
    });

    let mut begin_count = 0usize;
    let begin_event = loop {
        let event = timeout(Duration::from_secs(5), rx.recv())
            .await
            .expect("timed out waiting for begin event")
            .expect("begin event missing");
        if let EventMsg::ExecCommandBegin(begin) = event.msg
            && begin.call_id == call_id
        {
            begin_count += 1;
            break begin;
        }
    };

    let approval_event = loop {
        let event = timeout(Duration::from_secs(5), rx.recv())
            .await
            .expect("timed out waiting for retry approval request")
            .expect("retry approval request missing");
        match event.msg {
            EventMsg::ExecCommandBegin(begin) if begin.call_id == call_id => {
                begin_count += 1;
            }
            EventMsg::ExecApprovalRequest(request) if request.call_id == call_id => {
                break request;
            }
            _ => {}
        }
    };

    assert_eq!(begin_count, 1);
    assert_eq!(begin_event.command, requested_command);
    assert_eq!(approval_event.command, requested_command);

    session
        .notify_approval(
            &call_id,
            ReviewDecision::ApprovedOverrideCommand {
                command: override_command.clone(),
            },
        )
        .await;

    let end_event = loop {
        let event = timeout(Duration::from_secs(5), rx.recv())
            .await
            .expect("timed out waiting for exec end event")
            .expect("exec end event missing");
        match event.msg {
            EventMsg::ExecCommandBegin(begin) if begin.call_id == call_id => {
                begin_count += 1;
            }
            EventMsg::ExecCommandEnd(end) if end.call_id == call_id => {
                break end;
            }
            _ => {}
        }
    };

    let response = timeout(Duration::from_secs(5), handle)
        .await
        .expect("timed out waiting for shell handler")
        .expect("shell handler join error");

    let duration_seconds = (end_event.duration.as_secs_f32() * 10.0).round() / 10.0;
    let expected_body = serde_json::json!({
        "output": end_event.aggregated_output,
        "metadata": {
            "exit_code": end_event.exit_code,
            "duration_seconds": duration_seconds,
        },
        "executed_command": override_command,
    });
    let tool_output = match response {
        Ok(output) => tool_output_text(&output),
        Err(crate::function_tool::FunctionCallError::RespondToModel(message)) => message,
        Err(err) => panic!("unexpected shell handler error: {err:?}"),
    };

    assert_eq!(begin_count, 1);
    assert_eq!(
        end_event.command,
        expected_body["executed_command"]
            .as_array()
            .expect("array")
            .iter()
            .map(|value| value.as_str().expect("string").to_string())
            .collect::<Vec<_>>()
    );
    assert_eq!(
        serde_json::from_str::<serde_json::Value>(&tool_output).expect("valid json"),
        expected_body
    );
}

#[tokio::test]
async fn shell_handler_retry_override_reapplies_sandbox_selection() {
    let (session, mut turn_context, rx) = make_session_and_context_with_rx().await;
    *session.active_turn.lock().await = Some(ActiveTurn::default());
    Arc::get_mut(&mut turn_context)
        .expect("single turn context ref")
        .approval_policy
        .set(AskForApproval::OnFailure)
        .expect("test setup should allow updating approval policy");

    let temp_dir = tempfile::tempdir_in(
        turn_context
            .cwd
            .parent()
            .expect("workspace cwd should have a parent"),
    )
    .expect("create temp dir outside workspace");
    let requested_path = temp_dir.path().join("requested-outside-sandbox.txt");
    let override_path = temp_dir.path().join("override-outside-sandbox.txt");
    std::fs::write(&requested_path, b"requested should stay sandboxed\n")
        .expect("write requested file");
    std::fs::write(&override_path, b"override should stay sandboxed\n")
        .expect("write override file");

    let requested_command = if cfg!(windows) {
        vec![
            "cmd.exe".to_string(),
            "/C".to_string(),
            format!("type \"{}\"", requested_path.display()),
        ]
    } else {
        vec!["/bin/cat".to_string(), requested_path.display().to_string()]
    };
    let override_command = if cfg!(windows) {
        vec![
            "cmd.exe".to_string(),
            "/C".to_string(),
            format!("type \"{}\"", override_path.display()),
        ]
    } else {
        vec!["/bin/cat".to_string(), override_path.display().to_string()]
    };

    let tracker = Arc::new(tokio::sync::Mutex::new(TurnDiffTracker::new()));
    let call_id = "call-retry-override-sandboxed".to_string();
    let handler = ShellHandler;
    let handle: tokio::task::JoinHandle<
        Result<crate::tools::context::FunctionToolOutput, crate::function_tool::FunctionCallError>,
    > = tokio::spawn({
        let session = Arc::clone(&session);
        let turn_context = Arc::clone(&turn_context);
        let tracker = Arc::clone(&tracker);
        let requested_command = requested_command.clone();
        let call_id = call_id.clone();
        async move {
            handler
                .handle(ToolInvocation {
                    session,
                    turn: turn_context.clone(),
                    tracker,
                    call_id: call_id.clone(),
                    tool_name: "shell".to_string(),
                    tool_namespace: None,
                    payload: ToolPayload::Function {
                        arguments: serde_json::json!({
                            "command": requested_command,
                            "workdir": Some(turn_context.cwd.to_string_lossy().to_string()),
                            "timeout_ms": 1_000u64,
                            "sandbox_permissions": SandboxPermissions::UseDefault,
                        })
                        .to_string(),
                    },
                })
                .await
        }
    });

    let begin_event = loop {
        let event = timeout(Duration::from_secs(5), rx.recv())
            .await
            .expect("timed out waiting for begin event")
            .expect("begin event missing");
        if let EventMsg::ExecCommandBegin(begin) = event.msg
            && begin.call_id == call_id
        {
            break begin;
        }
    };

    let approval_event = loop {
        let event = timeout(Duration::from_secs(5), rx.recv())
            .await
            .expect("timed out waiting for retry approval request")
            .expect("retry approval request missing");
        if let EventMsg::ExecApprovalRequest(request) = event.msg
            && request.call_id == call_id
        {
            break request;
        }
    };

    assert_eq!(begin_event.command, requested_command);
    assert_eq!(approval_event.command, requested_command);

    session
        .notify_approval(
            &call_id,
            ReviewDecision::ApprovedOverrideCommand {
                command: override_command.clone(),
            },
        )
        .await;

    let end_event = loop {
        let event = timeout(Duration::from_secs(5), rx.recv())
            .await
            .expect("timed out waiting for exec end event")
            .expect("exec end event missing");
        if let EventMsg::ExecCommandEnd(end) = event.msg
            && end.call_id == call_id
        {
            break end;
        }
    };

    let response = timeout(Duration::from_secs(5), handle)
        .await
        .expect("timed out waiting for shell handler")
        .expect("shell handler join error");

    assert!(
        response.is_err(),
        "shell handler should keep override command sandboxed"
    );

    assert_eq!(end_event.status, ExecCommandStatus::Failed);
    assert_eq!(end_event.command, override_command);
}
